### ISSUE TITLE
TypeError: sourceMap.map.originalPositionFor is not a function

### ISSUE THREAD

**Issue by ariutta** [wikipathways/pvjs#436]
`gpml2pvjson` converts WP484_71773.gpml to json, but pvjs can't convert the json to svg.

`./bin/gpml2 /home/wikipathways.org/images/wikipathways/3/30/WP484_71773.gpml WP484_71773.svg`

gives this error:

```
err

/nix/store/4ipmjdyjif8qs18l88an4swq27sqyir6-node-_at_wikipathways_slash_pvjs-4.0.4/lib/node_modules/@wikipathways/pvjs/node_modules/source-map-support/source-map-support.js:214
    var originalPosition = sourceMap.map.originalPositionFor(position);
                                         ^
TypeError: sourceMap.map.originalPositionFor is not a function 
    at mapSourcePosition (/nix/store/4ipmjdyjif8qs18l88an4swq27sqyir6-node-_at_wikipathways_slash_pvjs-4.0.4/lib/node_modules/@wikipathways/pvjs/node_modules/source-map-support/source-map-support.js:214:42) 
    at wrapCallSite (/nix/store/4ipmjdyjif8qs18l88an4swq27sqyir6-node-_at_wikipathways_slash_pvjs-4.0.4/lib/node_modules/@wikipathways/pvjs/node_modules/source-map-support/source-map-support.js:358:20) 
    at /nix/store/4ipmjdyjif8qs18l88an4swq27sqyir6-node-_at_wikipathways_slash_pvjs-4.0.4/lib/node_modules/@wikipathways/pvjs/node_modules/source-map-support/source-map-support.js:395:26
    at Array.map (<anonymous>) 
    at Function.prepareStackTrace (/nix/store/4ipmjdyjif8qs18l88an4swq27sqyir6-node-_at_wikipathways_slash_pvjs-4.0.4/lib/node_modules/@wikipathways/pvjs/node_modules/source-map-support/source-map-support.js:394:24)
    at formatError (util.js:610:16)
    at formatValue (util.js:513:16)
    at inspect (util.js:294:10)
    at format (util.js:161:12)
    at Console.warn (console.js:145:21)
```

**Comment by ariutta** [comment]
Same error for this pathway:
/home/wikipathways.org/images/wikipathways/3/39/WP3197_80784.gpml
